#!/bin/bash

set -e
YADM_DIR=${HOME}/.config/yadm
if [ ! -d "${YADM_DIR}" ]; then
    echo "YADM directory not found, I'm confused"
    exit 1
fi

# check if zsh installed
if [ -z "$(command -v zsh)" ]; then
    echo "zsh not installed"
    if "${YADM_DIR}"/zsh_install; then
        echo "zsh_install failed!"
        exit 1
    fi
else
    echo "zsh already installed"
fi

"${YADM_DIR}"/omz_install.zsh

# start a new shell to ensure omz is loaded
zsh -c 'source ${HOME}/.zshrc'
zsh "${YADM_DIR}/p10k_install.zsh"

exit

NVIM_CONFIG_PATH="$HOME/.config/nvim"
mkdir -p "$NVIM_CONFIG_PATH"
if [ "$(ls -A $NVIM_CONFIG_PATH)" ]; then
    echo "Neovim folder not empty"
else
    git clone git@github.com:d-3nnis/dvim.git ~/.config/nvim/
fi

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
        if ! "$bootstrap"; then
            echo "Error: bootstrap '$bootstrap' failed" >&2
            exit 1
        fi
    fi
done
