#!/bin/bash

set -e
YADM_DIR=${HOME}/.config/yadm
if [ ! -d "${YADM_DIR}" ]; then
    echo "YADM directory not found, I'm confused"
    exit 1
fi

# check if zsh installed
if [ -z "$(command -v zsh)" ]; then
    echo "zsh not installed"
    if "${YADM_DIR}"/zsh_install; then
        echo "zsh_install failed!"
        exit 1
    fi
else
    echo "zsh already installed"
    rm ~/.zshrc
fi

"${YADM_DIR}"/omz_install.zsh
"${YADM_DIR}"/p10k_install.zsh
"${YADM_DIR}"/fzf_install.zsh
"${YADM_DIR}"/zsh_plugin_setup.zsh

NVIM_CONFIG_PATH="$HOME/.config/nvim"
mkdir -p "$NVIM_CONFIG_PATH"
if [ "$(ls -A ${NVIM_CONFIG_PATH})" ]; then
    echo "Neovim folder not empty"
else
    git clone git@github.com:d-3nnis/dvim.git ~/.config/nvim/
fi

